{ pkgs 
, inputs
, stable
, ...
}:
{
  home.packages = with pkgs; [
    over-google-chrome
    vesktop
    veracrypt
    #gpu-screen-recorder-gtk
    #gpu-screen-recorder
    over-gpu-screen-recorder
    gnome-tweaks
    pavucontrol
    helvum
    qadwaitadecorations
    qadwaitadecorations-qt6
    adw-gtk3
    droidcam
    mangohud
    tor
    stable.mission-center
    lutris
    fastfetch
    kdenlive
    dconf-editor
    celluloid
    mpv
    vlc
    heroic
    yt-dlp
    ffmpeg
    qbittorrent
    onlyoffice-bin
    bat
    tty-clock
    todoist-electron
    krita
    gamescope
    nekoray
    jetbrains.idea-ultimate
    jetbrains.webstorm
    jetbrains.pycharm-professional
    nodejs_22
    php
    vkbasalt
    stable.cava
    antimicrox
    appimage-run
    waydroid
    blanket
    protonplus
    whatsapp-for-linux
    tor-browser
    cassette
    unigine-superposition
    onefetch
    gimp
    rewaita
    telegram-desktop
    ffmpegthumbnailer
    xdragon
    tmate
    blender-hip
    android-tools
    numix-icon-theme
  ];
}
