{
  imports = [
    ./mangohud
    #./steam
    ./eza
    ./fzf
    ./zoxide
    ./fish
    ./vscode
    ./ranger
    ./autostart
    ./neovim
    ./vkBasalt
    ./virtmanager
    ./fastfetch
    ./desktop-override/obs
    ./desktop-override/vesktop
    ./desktop-override/heroic
  ];
}